import { DASHBOARD } from "./constants";

export const SET_NEW_PLAYTLIST_MODAL = `${DASHBOARD}/SET_NEW_PLAYTLIST_MODAL`;
export const SET_ADD_VIDEO_MODAL = `${DASHBOARD}/SET_ADD_VIDEO_MODAL`;

export const GET_USER_PLAYLISTS = `${DASHBOARD}/GET_USER_PLAYLISTS`;
export const SET_USER_PLAYLIST = `${DASHBOARD}/SET_USER_PLAYLIST`;

export const GET_PLAYLIST_MEDIA = `${DASHBOARD}/GET_PLAYLIST_MEDIA`;
export const SET_PLAYLIST_MEDIA = `${DASHBOARD}/SET_PLAYLIST_MEDIA`;

export const SET_CURRENT_PLAYLIST = `${DASHBOARD}/SET_CURRENT_PLAYLIST`;
