import { DASHBOARD } from "./constants";

export const SET_NEW_PLAYTLIST_MODAL = `${DASHBOARD}/SET_NEW_PLAYTLIST_MODAL`;
export const SET_ADD_VIDEO_MODAL = `${DASHBOARD}/SET_ADD_VIDEO_MODAL`;

export const GET_USER_PLAYLISTS = `${DASHBOARD}/GET_USER_PLAYLISTS`;
export const SET_USER_PLAYLIST = `${DASHBOARD}/SET_USER_PLAYLIST`;

export const GET_PLAYLIST_MEDIA = `${DASHBOARD}/GET_PLAYLIST_MEDIA`;
export const SET_PLAYLIST_MEDIA = `${DASHBOARD}/SET_PLAYLIST_MEDIA`;

export const SET_CURRENT_PLAYLIST = `${DASHBOARD}/SET_CURRENT_PLAYLIST`;

export const SET_NEW_PLAYLIST = `${DASHBOARD}/SET_NEW_PLAYLIST`;
export const POST_NEW_PLAYLIST = `${DASHBOARD}/POST_NEW_PLAYLIST`;
export const CLEAN_NEW_PLAYLIST = `${DASHBOARD}/CLEAN_NEW_PLAYLIST`;

export const POST_UPDATE_PLAYLIST = `${DASHBOARD}/POST_UPDATE_PLAYLIST`;

export const SET_LAMBDA_MEDIA = `${DASHBOARD}/SET_LAMBDA_MEDIA`;
export const POST_LAMBDA_MEDIA = `${DASHBOARD}/POST_LAMBDA_MEDIA`;
