import { DASHBOARD } from "./constants";

export const SET_NEW_PLAYTLIST_MODAL = `${DASHBOARD}/SET_NEW_PLAYTLIST_MODAL`;
export const SET_ADD_VIDEO_MODAL = `${DASHBOARD}/SET_ADD_VIDEO_MODAL`;
export const SET_PROFILE_MODAL = `${DASHBOARD}/SET_PROFILE_MODAL`;
export const SET_DELETE_PLAYLIST_MODAL = `${DASHBOARD}/SET_DELETE_PLAYLIST_MODAL`;

export const GET_USER_PLAYLISTS = `${DASHBOARD}/GET_USER_PLAYLISTS`;
export const SET_USER_PLAYLIST = `${DASHBOARD}/SET_USER_PLAYLIST`;

export const GET_PLAYLIST_MEDIA = `${DASHBOARD}/GET_PLAYLIST_MEDIA`;
export const SET_PLAYLIST_MEDIA = `${DASHBOARD}/SET_PLAYLIST_MEDIA`;

export const SET_CURRENT_PLAYLIST = `${DASHBOARD}/SET_CURRENT_PLAYLIST`;

export const SET_NEW_PLAYLIST = `${DASHBOARD}/SET_NEW_PLAYLIST`;
export const POST_NEW_PLAYLIST = `${DASHBOARD}/POST_NEW_PLAYLIST`;
export const CLEAN_NEW_PLAYLIST = `${DASHBOARD}/CLEAN_NEW_PLAYLIST`;

export const POST_UPDATE_PLAYLIST = `${DASHBOARD}/POST_UPDATE_PLAYLIST`;

export const SET_LAMBDA_MEDIA = `${DASHBOARD}/SET_LAMBDA_MEDIA`;
export const POST_LAMBDA_MEDIA = `${DASHBOARD}/POST_LAMBDA_MEDIA`;
export const SHOW_LAMBA_RESULTS = `${DASHBOARD}/SHOW_LAMBA_RESULTS`;
export const SET_CURRENT_MEDIA = `${DASHBOARD}/SET_CURRENT_MEDIA"`;

export const POST_DELETE_MEDIA = `${DASHBOARD}/POST_DELETE_MEDIA`;
export const POST_ADD_MEDIA = `${DASHBOARD}/POST_ADD_MEDIA`;

export const POST_UPDATE_USER_PROFILE = `${DASHBOARD}/POST_UPDATE_USER_PROFILE`;
export const POST_CHANGE_PASSWORD = `${DASHBOARD}/POST_CHANGE_PASSWORD`;

export const POST_DELETE_PLAYLIST = `${DASHBOARD}/POST_DELETE_PLAYLIST`;

// Loaders
export const SET_LAMBDA_LOADER = `${DASHBOARD}/SET_LAMBDA_LOADER`;
export const SET_FORGOT_PASS_LOADER = `${DASHBOARD}/SET_FORGOT_PASS_LOADER`;
export const SET_LOGIN_LOADER = `${DASHBOARD}/SET_LOGIN_LOADER`;
export const SET_REGISTER_LOADER = `${DASHBOARD}/SET_REGISTER_LOADER`;
export const SET_CREATE_PLAYLIST_LOADER = `${DASHBOARD}/SET_CREATE_PLAYLIST_LOADER`;
export const SET_ADD_MEDIA_LOADER = `${DASHBOARD}/SET_ADD_MEDIA_LOADER`;
export const SET_DELETE_MEDIA_LOADER = `${DASHBOARD}/SET_DELETE_MEDIA_LOADER`;
export const SET_USER_PROFILE_LOADER = `${DASHBOARD}/SET_USER_PROFILE_LOADER`;
export const SET_DELETE_PLAYLIST_LOADER = `${DASHBOARD}/SET_DELETE_PLAYLIST_LOADER`;
