import { EXPLORE } from "./constants";

export const SET_SEARCH_INPUT = `${EXPLORE}/SET_SEARCH_INPUT`;
export const SEARCH_USER = `${EXPLORE}/SEARCH_USER`;
export const SET_SEARCH_RESULTS = `${EXPLORE}/SET_SEARCH_RESULTS`;
export const SET_SEARCH_LOADER = `${EXPLORE}/SET_SEARCH_LOADER`;

export const FIND_PROFILE = `${EXPLORE}/FIND_PROFILE`;
export const SET_FOUND_PROFILE = `${EXPLORE}/SET_FOUND_PROFILE`;

export const FIND_USER_PLAYLISTS = `${EXPLORE}/FIND_USER_PLAYLISTS`;
export const SET_FOUND_USER_PLAYLISTS = `${EXPLORE}/SET_FOUND_USER_PLAYLISTS`;

export const GET_PUBLIC_PLAYLIST_MEDIA = `${EXPLORE}/GET_PUBLIC_PLAYLIST_MEDIA`;
